name: guard_clauses
description: Package containing guard clauses that can help functions "fail fast" by verifying method contracts.
version: 0.1.1
repository: https://github.com/chrishibler/guard_clauses
issue_tracker: https://github.com/chrishibler/guard_clauses/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  test: ^1.20.2
